import type { L10n } from "@/lib/i18n";

/**
 * La sezione «Come vorresti valorizzarti?» del sito originale è un elenco piatto
 * di oltre 200 voci divise per zona del corpo. Qui la stessa tassonomia diventa
 * dati: le etichette stanno in un dizionario unico (molte voci si ripetono in
 * più zone) e ogni zona referenzia le sue chiavi.
 */
export const procedureLabels = {
  mesoterapia: {
    it: "Mesoterapia, bioristrutturazione, biorivitalizzazione e biostimolazione",
    en: "Mesotherapy, bio-restructuring, bio-revitalisation and bio-stimulation",
  },
  prp: {
    it: "Mesoterapia avanzata con fattori di crescita piastrinici PRP (plasma ricco in piastrine)",
    en: "Advanced mesotherapy with PRP platelet growth factors (platelet-rich plasma)",
  },
  dermaroller: { it: "Dermaroller (meso-needling)", en: "Dermaroller (meso-needling)" },
  celebritylift: {
    it: "CelebrityLift Laser con cosmeceutici dedicati",
    en: "CelebrityLift Laser with dedicated cosmeceuticals",
  },
  led: { it: "LED medicale", en: "Medical LED" },
  ledEndolyft: { it: "LED con cosmeceutici Endolyft®", en: "LED with Endolyft® cosmeceuticals" },
  newLift: {
    it: "New Lift Laser con cosmeceutici Endolyft®",
    en: "New Lift Laser with Endolyft® cosmeceuticals",
  },
  peeling: { it: "Peeling", en: "Peeling" },
  peelingProfondo: {
    it: "Peeling (superficiale, medio, profondo)",
    en: "Peeling (superficial, medium, deep)",
  },
  carbossiterapia: { it: "Carbossiterapia", en: "Carboxytherapy" },
  biodermogenesi: { it: "Biodermogenesi", en: "Biodermogenesis" },
  bionutrilift: { it: "BioNutriLift", en: "BioNutriLift" },
  bioNutriKnees: { it: "Bio-Nutri-Knees", en: "Bio-Nutri-Knees" },
  ultherapy: {
    it: "Ultherapy® (lifting non chirurgico), ultrasuoni microfocalizzati con sistema di visione",
    en: "Ultherapy® (non-surgical lifting), micro-focused ultrasound with visualisation",
  },
  cellfina: {
    it: "Cellfina® (trattamento a lungo termine della cellulite)",
    en: "Cellfina® (long-term cellulite treatment)",
  },
  endolift: { it: "Endolift®", en: "Endolift®" },
  fili: {
    it: "Fili biostimolanti e liftanti riassorbibili extra-sottili, senza accesso chirurgico",
    en: "Extra-fine absorbable bio-stimulating and lifting threads, without surgical access",
  },
  botoxRughe: {
    it: "Tossina botulinica (Botox) per rughe del volto e del collo",
    en: "Botulinum toxin (Botox) for facial and neck wrinkles",
  },
  botoxBruxismo: {
    it: "Tossina botulinica (Botox) per bruxismo",
    en: "Botulinum toxin (Botox) for bruxism",
  },
  botoxGenitale: {
    it: "Tossina botulinica (Botox) per disordini della sfera genitale",
    en: "Botulinum toxin (Botox) for genital-area disorders",
  },
  fillerRimodellare: {
    it: "Filler all'acido ialuronico per rimodellare",
    en: "Hyaluronic acid filler for reshaping",
  },
  fillerLabbra: {
    it: "Filler all'acido ialuronico per le labbra o labioplastica",
    en: "Hyaluronic acid filler for the lips, or lip augmentation",
  },
  fillerZigomi: {
    it: "Filler all'acido ialuronico per gli zigomi o malaroplastica",
    en: "Hyaluronic acid filler for the cheekbones, or malarplasty",
  },
  fillerMento: {
    it: "Filler all'acido ialuronico per il mento o mentoplastica",
    en: "Hyaluronic acid filler for the chin, or genioplasty",
  },
  fillerContorno: {
    it: "Filler all'acido ialuronico per il contorno labbra («codice a barre») e il contorno occhi («zampe di gallina»)",
    en: "Hyaluronic acid filler for the lip contour («barcode lines») and eye contour («crow's feet»)",
  },
  fillerNaso: {
    it: "Filler all'acido ialuronico per il naso: rinofiller o rinoplastica liquida",
    en: "Hyaluronic acid filler for the nose: rhinofiller or liquid rhinoplasty",
  },
  fillerPuntoG: {
    it: "Filler all'acido ialuronico per il punto G",
    en: "Hyaluronic acid filler for the G-spot",
  },
  laserFrazionato: {
    it: "Ringiovanimento con laser frazionato non ablativo",
    en: "Rejuvenation with non-ablative fractional laser",
  },
  laserCo2: {
    it: "Ringiovanimento con laser frazionato ablativo CO₂",
    en: "Rejuvenation with ablative CO₂ fractional laser",
  },
  laserAcne: {
    it: "Trattamento laser dell'acne in fase attiva",
    en: "Laser treatment of active acne",
  },
  laserCicatriciAcne: {
    it: "Trattamento laser delle cicatrici da acne",
    en: "Laser treatment of acne scarring",
  },
  laserVascolari: {
    it: "Trattamento laser di patologie vascolari",
    en: "Laser treatment of vascular conditions",
  },
  laserNeoformazioni: {
    it: "Trattamento laser di neoformazioni cutanee",
    en: "Laser treatment of skin lesions",
  },
  laserNeoformazioniCorpo: {
    it: "Trattamento laser di neoformazioni cutanee del corpo",
    en: "Laser treatment of skin lesions on the body",
  },
  laserSmagliature: {
    it: "Trattamento laser delle smagliature",
    en: "Laser treatment of stretch marks",
  },
  laserMacchie: {
    it: "Trattamento laser delle macchie cutanee",
    en: "Laser treatment of skin pigmentation",
  },
  laserRoncopatia: {
    it: "Trattamento laser della roncopatia (russamento e apnee del sonno)",
    en: "Laser treatment of snoring and sleep apnoea",
  },
  laserAntalgica: {
    it: "Laser terapia antalgica (trigger point)",
    en: "Analgesic laser therapy (trigger points)",
  },
  dermamelan: { it: "Dermamelan® per le macchie cutanee", en: "Dermamelan® for skin pigmentation" },
  acnelan: { it: "Acnelan® per il trattamento dell'acne", en: "Acnelan® for acne treatment" },
  criolipolisi: { it: "Criolipolisi", en: "Cryolipolysis" },
  intralipoterapia: {
    it: "Intralipoterapia per ridurre le adiposità localizzate",
    en: "Intralipotherapy to reduce localised fat deposits",
  },
  mesoCellulite: { it: "Mesoterapia per la cellulite", en: "Mesotherapy for cellulite" },
  scleroterapiaCapillari: {
    it: "Scleroterapia e sclero-mousse dei capillari",
    en: "Sclerotherapy and sclero-mousse for thread veins",
  },
  scleroterapia: { it: "Scleroterapia, sclero-mousse", en: "Sclerotherapy, sclero-mousse" },
  ladylift: {
    it: "LadyLift®: ringiovanimento vulvare e vaginale",
    en: "LadyLift®: vulvar and vaginal rejuvenation",
  },
  gShot: { it: "G-Shot: trattamento del punto G", en: "G-Shot: G-spot treatment" },
  pShot: {
    it: "P-Shot: aumento della consistenza e ingrandimento del pene",
    en: "P-Shot: penile firmness and enlargement",
  },
} satisfies Record<string, L10n>;

export type ProcedureKey = keyof typeof procedureLabels;

export interface Zone {
  id: string;
  name: L10n;
  /** icona Lucide usata nella griglia di selezione */
  icon: string;
  note?: L10n;
  procedures: ProcedureKey[];
}

export const zones: Zone[] = [
  {
    id: "capelli",
    icon: "Sparkles",
    name: { it: "Capelli e cuoio capelluto", en: "Hair and scalp" },
    procedures: [
      "mesoterapia",
      "prp",
      "dermaroller",
      "celebritylift",
      "led",
      "laserNeoformazioni",
      "peeling",
      "laserMacchie",
      "dermamelan",
      "carbossiterapia",
    ],
  },
  {
    id: "volto-collo",
    icon: "Smile",
    name: { it: "Volto e collo", en: "Face and neck" },
    procedures: [
      "ultherapy",
      "botoxRughe",
      "botoxBruxismo",
      "fili",
      "fillerRimodellare",
      "fillerLabbra",
      "fillerZigomi",
      "fillerMento",
      "fillerContorno",
      "fillerNaso",
      "bionutrilift",
      "peeling",
      "mesoterapia",
      "prp",
      "dermaroller",
      "carbossiterapia",
      "biodermogenesi",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "celebritylift",
      "led",
      "laserAcne",
      "laserCicatriciAcne",
      "laserVascolari",
      "laserNeoformazioni",
      "laserRoncopatia",
      "criolipolisi",
      "intralipoterapia",
      "laserMacchie",
      "dermamelan",
      "acnelan",
    ],
  },
  {
    id: "addome",
    icon: "Shirt",
    name: { it: "Addome", en: "Abdomen" },
    procedures: [
      "ultherapy",
      "fili",
      "peeling",
      "mesoterapia",
      "prp",
      "dermaroller",
      "carbossiterapia",
      "biodermogenesi",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "celebritylift",
      "led",
      "laserVascolari",
      "laserNeoformazioniCorpo",
      "laserSmagliature",
      "criolipolisi",
      "intralipoterapia",
      "laserMacchie",
      "dermamelan",
    ],
  },
  {
    id: "mammelle",
    icon: "Heart",
    name: { it: "Mammelle", en: "Breasts" },
    procedures: [
      "fili",
      "peeling",
      "mesoterapia",
      "prp",
      "dermaroller",
      "carbossiterapia",
      "biodermogenesi",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "celebritylift",
      "led",
      "laserVascolari",
      "laserNeoformazioni",
      "laserSmagliature",
      "criolipolisi",
      "intralipoterapia",
      "laserMacchie",
      "dermamelan",
    ],
  },
  {
    id: "glutei",
    icon: "CircleDot",
    name: { it: "Glutei", en: "Buttocks" },
    procedures: [
      "ultherapy",
      "cellfina",
      "fili",
      "fillerRimodellare",
      "peelingProfondo",
      "mesoterapia",
      "mesoCellulite",
      "prp",
      "dermaroller",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "newLift",
      "ledEndolyft",
      "laserVascolari",
      "laserNeoformazioni",
      "laserSmagliature",
      "criolipolisi",
      "intralipoterapia",
    ],
  },
  {
    id: "ginocchia",
    icon: "MoveVertical",
    name: { it: "Ginocchia", en: "Knees" },
    procedures: [
      "ultherapy",
      "fili",
      "fillerRimodellare",
      "peeling",
      "mesoterapia",
      "prp",
      "dermaroller",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "newLift",
      "ledEndolyft",
      "laserVascolari",
      "laserNeoformazioni",
      "laserSmagliature",
      "criolipolisi",
      "intralipoterapia",
      "scleroterapiaCapillari",
      "laserMacchie",
      "dermamelan",
      "bioNutriKnees",
    ],
  },
  {
    id: "braccia-cosce",
    icon: "MoveHorizontal",
    name: { it: "Interno braccia e interno cosce", en: "Inner arms and inner thighs" },
    procedures: [
      "ultherapy",
      "fili",
      "fillerRimodellare",
      "peeling",
      "mesoterapia",
      "mesoCellulite",
      "prp",
      "dermaroller",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "newLift",
      "ledEndolyft",
      "laserNeoformazioni",
      "laserSmagliature",
      "criolipolisi",
      "intralipoterapia",
    ],
  },
  {
    id: "mani-piedi",
    icon: "Hand",
    name: { it: "Mani e piedi", en: "Hands and feet" },
    procedures: [
      "ultherapy",
      "fili",
      "fillerRimodellare",
      "peeling",
      "mesoterapia",
      "prp",
      "dermaroller",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "newLift",
      "ledEndolyft",
      "laserVascolari",
      "laserNeoformazioni",
      "intralipoterapia",
      "laserMacchie",
      "dermamelan",
    ],
  },
  {
    id: "genitali-femminili",
    icon: "Venus",
    name: { it: "Genitali femminili", en: "Female genitals" },
    note: {
      it: "Sono costituiti dal canale vaginale e dalla vulva, formata a sua volta dal monte di Venere, la clitoride, le grandi e piccole labbra e l'imene.",
      en: "These comprise the vaginal canal and the vulva, which in turn is formed by the mons pubis, the clitoris, the labia majora and minora and the hymen.",
    },
    procedures: [
      "botoxGenitale",
      "fili",
      "fillerRimodellare",
      "fillerPuntoG",
      "mesoterapia",
      "prp",
      "laserFrazionato",
      "laserCo2",
      "endolift",
      "newLift",
      "ledEndolyft",
      "laserVascolari",
      "laserNeoformazioni",
      "intralipoterapia",
      "ladylift",
      "gShot",
    ],
  },
  {
    id: "genitali-maschili",
    icon: "Mars",
    name: { it: "Genitali maschili", en: "Male genitals" },
    note: {
      it: "Sono costituiti dal pene e dallo scroto, la sacca che racchiude i testicoli, gli epididimi e la parte iniziale del funicolo spermatico.",
      en: "These comprise the penis and the scrotum, the sac containing the testicles, the epididymis and the first section of the spermatic cord.",
    },
    procedures: [
      "botoxGenitale",
      "fili",
      "fillerRimodellare",
      "mesoterapia",
      "prp",
      "laserFrazionato",
      "laserCo2",
      "laserVascolari",
      "laserNeoformazioni",
      "laserMacchie",
      "dermamelan",
      "pShot",
    ],
  },
  {
    id: "altri",
    icon: "Stethoscope",
    name: { it: "Altri trattamenti", en: "Other treatments" },
    procedures: ["laserAntalgica", "laserRoncopatia", "scleroterapia"],
  },
];

/** «Cosa vuoi migliorare di te?» — l'elenco chirurgico, dalla pagina Chirurgia Estetica. */
export interface SurgicalGroup {
  id: string;
  name: L10n;
  items: L10n[];
}

export const surgicalGroups: SurgicalGroup[] = [
  {
    id: "volto-collo",
    name: { it: "Chirurgia del volto e del collo", en: "Face and neck surgery" },
    items: [
      { it: "Blefaroplastica superiore e/o inferiore (chirurgia delle palpebre)", en: "Upper and/or lower blepharoplasty (eyelid surgery)" },
      { it: "Blefaroplastica superiore e/o inferiore laser assistita", en: "Laser-assisted upper and/or lower blepharoplasty" },
      { it: "Blefaroplastica transcongiuntivale laser assistita", en: "Laser-assisted transconjunctival blepharoplasty" },
      { it: "Rinoplastica e/o settoplastica (chirurgia del naso)", en: "Rhinoplasty and/or septoplasty (nasal surgery)" },
      { it: "Riduzione dei turbinati", en: "Turbinate reduction" },
      { it: "Chirurgia della punta del naso", en: "Nasal tip surgery" },
      { it: "Lifting del volto", en: "Facelift" },
      { it: "Mini-lifting del volto", en: "Mini facelift" },
      { it: "Lifting del collo", en: "Neck lift" },
      { it: "Lifting delle sopracciglia o brow-lift", en: "Brow lift" },
      { it: "Cantopessi", en: "Canthopexy" },
      { it: "Labioplastica o cheiloplastica (chirurgia delle labbra)", en: "Lip surgery (cheiloplasty)" },
      { it: "Malaroplastica (chirurgia degli zigomi)", en: "Malarplasty (cheekbone surgery)" },
      { it: "Mentoplastica (chirurgia del mento)", en: "Genioplasty (chin surgery)" },
      { it: "Otoplastica (chirurgia delle orecchie)", en: "Otoplasty (ear surgery)" },
      { it: "Ricostruzione dei lobi auricolari", en: "Earlobe reconstruction" },
      { it: "Chirurgia del contorno mandibolare", en: "Jawline contouring surgery" },
    ],
  },
  {
    id: "capelli",
    name: { it: "Chirurgia dei capelli", en: "Hair surgery" },
    items: [
      { it: "Autotrapianto di capelli, tecnica STRIP", en: "Hair transplant, STRIP technique" },
      { it: "Autotrapianto di capelli, tecnica FUE", en: "Hair transplant, FUE technique" },
      { it: "Trapianto di capelli artificiali BIOFIBRE", en: "BIOFIBRE artificial hair implant" },
    ],
  },
  {
    id: "seno",
    name: { it: "Chirurgia del seno", en: "Breast surgery" },
    items: [
      { it: "Mastoplastica additiva, riduttiva e ricostruttiva", en: "Breast augmentation, reduction and reconstruction" },
      { it: "Mastopessi (sollevamento delle mammelle)", en: "Mastopexy (breast lift)" },
      { it: "Riduzione della ginecomastia o pseudo-ginecomastia", en: "Gynaecomastia or pseudo-gynaecomastia reduction" },
      { it: "Correzione di capezzoli asimmetrici e introflessi", en: "Correction of asymmetric and inverted nipples" },
      { it: "Chirurgia delle neoformazioni mammarie", en: "Surgery for breast lesions" },
      { it: "Simmetrizzazione delle mammelle", en: "Breast symmetrisation" },
    ],
  },
  {
    id: "corpo",
    name: { it: "Chirurgia del corpo", en: "Body surgery" },
    items: [
      { it: "Liposcultura e liposuzione laser delle adiposità localizzate (con aspirazione)", en: "Laser liposculpture and liposuction of localised fat (with aspiration)" },
      { it: "Laser lipolisi di piccole adiposità localizzate (senza aspirazione)", en: "Laser lipolysis of small fat deposits (without aspiration)" },
      { it: "Lifting e mini-lifting delle braccia (brachioplastica)", en: "Arm lift and mini arm lift (brachioplasty)" },
      { it: "Lifting dei glutei e delle cosce (torsoplastica)", en: "Buttock and thigh lift (torsoplasty)" },
      { it: "Lifting e mini-lifting dell'addome (addominoplastica)", en: "Abdominoplasty and mini abdominoplasty" },
      { it: "Rimodellamento di glutei e polpacci", en: "Buttock and calf remodelling" },
      { it: "Gluteoplastica con protesi, tecnica Gonzales", en: "Buttock augmentation with implants, Gonzales technique" },
      { it: "Lipofilling e lipostruttura", en: "Lipofilling and lipostructure" },
      { it: "Flebologia e chirurgia delle varici", en: "Phlebology and varicose vein surgery" },
      { it: "Fili di sospensione e di trazione con accesso chirurgico", en: "Suspension and traction threads with surgical access" },
    ],
  },
  {
    id: "intimita",
    name: { it: "Chirurgia dell'intimità", en: "Intimate surgery" },
    items: [
      { it: "Labioplastica vaginale (piccole o grandi labbra)", en: "Vaginal labiaplasty (labia minora or majora)" },
      { it: "Vaginal tightening cosmetico (restringimento post-partum)", en: "Cosmetic vaginal tightening (post-partum)" },
      { it: "Rinfoltimento dei peli pubici", en: "Pubic hair restoration" },
      { it: "Scrotoplastica", en: "Scrotoplasty" },
    ],
  },
  {
    id: "piccola-chirurgia",
    name: { it: "Piccola chirurgia", en: "Minor surgery" },
    items: [
      { it: "Asportazione di cisti con esame istologico", en: "Cyst removal with histological examination" },
      { it: "Asportazione di nei con esame istologico", en: "Mole removal with histological examination" },
      { it: "Asportazione di neoformazioni cutanee di volto e corpo con esame istologico", en: "Removal of skin lesions on face and body with histological examination" },
      { it: "Rimozione di granulomi da filler con laser in fibra ILT (Intralesional Laser Therapy)", en: "Removal of filler granulomas with ILT fibre laser (Intralesional Laser Therapy)" },
      { it: "Revisione di cicatrici", en: "Scar revision" },
    ],
  },
];
